### ISSUE TITLE
Question or bug with items.yml

### ISSUE THREAD

**Issue by PilgrimViis** [PedroJM96/SuperLobbyDeluxe#2]
Hello, I've stumbled on a problem. In my understanding, if I put something in items.yml it should do 2 things:
1. Add an item to a user when he joins the server
2. On a right click on the item, it should execute a command. In my case - open server menu.
I'm not getting either of those things. 
```yml
# items.yml
menu:
  name: '&8<3>  &6Menu &8<3>  &7(Right button)'
  material: COMPASS # I also tried other blocks, and a default one (SIGN)
  slot: 1
  commands:
  - 'player: menu' # I also tried just 'menu', 'say: hello' and some other commands
  delay: 5
  permission: superlobby.items.menu` # Yeah, I've added this permission. Also, I tried as player and as operator.
```
___________________________________________________
Server Version: Paper 1.18.2
plugin version: 4.5.2, downloaded from spigot
___________________________________________________

Can you please tell is it a bug, or I'm doing something wrong? Thank you.
